const { createElement: h } = React;

let navItems = [
  ['about', 'WHY TEAM4', 'რატომ თიმ ფორი'],
  ['book', 'I Am The Answer', '„მე ვარ პასუხი“'],
  ['programs', 'PROGRAMS', 'პროგრამები'],
  ['winspace', 'WinSpace', 'ვინსფეისი'],
  ['testimonials', 'Testimonials', 'შეფასებები'],
];

let copy = {
  ENG: {
    heroKicker: 'LASHA KHURTSIDZE / TEAM4 SALES COLLEGE',
    heroTitle: 'Sales Is Not Talent — It Is Psychology.',
    heroSubtitle: 'Sales • Negotiation • NLP • Digital Marketing',
    heroText: 'Performance-luxury sales education, negotiation strategy, and personal brand growth for leaders who want sharper influence, faster decisions, and measurable commercial results.',
    book: 'Book Consultation',
    openDoor: 'GO TO WINSPACE',
    resumeTitle: 'Short Resume',
    resumeText: [
      'Lasha Khurtsidze is a Commercial Director, Sales Strategist, Negotiation Expert, Author, and Founder of Team4 — Sales College & Training Center. With 15+ years of experience across the automotive industry, insurance, construction, hospitality, retail, and business development, he has built his career through real sales, negotiations, leadership, and team development.',
      'He started his career in direct sales and gradually moved into strategic and managerial roles, gaining deep insight into customer psychology, communication, influence, and business growth mechanisms. Over the years, he has managed sales departments, developed branches, worked with international partners, and created growth-oriented strategies in competitive markets.',
      'Lasha is also the author of “I Am The Answer” — a motivational and psychological work based on real experience, sales, leadership, faith, struggle, personal transformation, and the philosophy of success.',
      'Team4 was created not as a traditional training center, but as a space where sales, communication, negotiations, and influence are taught through real practice, not theory alone.',
    ],
    readMore: 'Read more',
    showLess: 'Show less',
    resumeBookCta: 'Buy The Book',
    aboutKicker: 'Why TEAM4',
    aboutTitle: 'Team4',
    aboutParagraphs: [
      'Team4 is not just another training center. It was built on real sales, negotiations, mistakes, pressure, and hands-on business experience. Our goal is not simply to hand people certificates — our goal is to transform the way they communicate, sell, negotiate, and think.',
      'We work with entrepreneurs, sales teams, managers, and companies that want real results, stronger communication, and highly effective teams. Through modern sales psychology, NLP techniques, negotiation strategies, and practical experience, we help people turn communication into influence and influence into business growth.',
      'What makes Team4 different is its practice-based learning approach. Every program is built around real business cases, customer psychology, objection handling, leadership, emotional intelligence, and strategic communication.',
      'Our philosophy is simple:\nSales is not manipulation — sales is understanding people.',
    ],
    servicesKicker: 'Services',
    servicesTitle: 'Premium Growth Systems',
    servicesText: 'Training, strategy, media, and outsourced commercial execution for teams that want a sharper edge.',
    coursesKicker: 'I Am The Answer',
    coursesTitle: 'I Am The Answer',
    coursesText: 'A motivational and psychological work based on real-life experience, sales, leadership, faith, struggle, personal transformation, and the philosophy of success. The book reflects the idea that success is not built only on skills — it is shaped by mindset, discipline, communication, and inner strength.',
    bookGalleryTitle: 'Book — “I Am Answer”',
    bookGallerySubtitle: 'Real experience, psychology, sales, struggle, and personal transformation.',
    purchaseSubtitle: 'Get the book — ‘I Am The Answer’',
    purchaseButton: 'Purchase',
    programsKicker: 'Services',
    programsTitle: 'Services',
    programsText: 'Premium commercial services for sales, marketing, media, and brand growth.',
    learnMore: 'Learn More',
    register: 'Register',
    eventKicker: 'WinSpace',
    eventTitle: 'WinSpace',
    eventText: 'WinSpace is a space where we talk about business, sales, leadership, and the real journey behind success.',
    eventFormat: 'Premium conversations',
    eventItems: ['Business', 'Sales', 'Leadership', 'The real journey behind success'],
    testimonialsKicker: 'Testimonials',
    testimonialsTitle: 'Trusted by people who take business seriously.',
    leaveComment: 'Leave a Comment',
    testimonialName: 'Name',
    testimonialRole: 'Position / Company',
    testimonialComment: 'Comment',
    testimonialSubmit: 'Submit',
    testimonialClose: 'Close',
    contactKicker: 'Contact',
    contactTitle: 'Remove the pink glasses. Learn real sales.',
    contactQuote: '“If you are ready to remove the pink glasses and learn real sales, contact me.”',
    contactText: 'For consultation, sales training, negotiation programs, or Open Door Day registration, send a direct request to Team4 Sales College.',
    contactStart: 'Start the conversation',
    phoneLabel: 'Phone',
    emailLabel: 'Email',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    selectedProgram: 'Selected Program',
    message: 'Message',
    contactMe: 'SEND',
    sending: 'Sending...',
    requiredMessage: 'Please fill in all required fields.',
    successMessage: 'Message sent successfully.',
    errorMessage: 'Message could not be sent. Check EmailJS configuration.',
  },
  GEO: {
    heroKicker: 'ლაშა ხურციძე / თიმ ფორი გაყიდვების კოლეჯი',
    heroTitle: 'გაყიდვები ტალანტი არ არის — ეს ფსიქოლოგიაა.',
    heroSubtitle: 'გაყიდვები • მოლაპარაკება • NLP • ციფრული მარკეტინგი',
    heroText:
      'თუ შენი გუნდი ბევრს მუშაობს, მაგრამ გაყიდვები მაინც არ იზრდება —\nპრობლემა პროდუქტში არა, კომუნიკაციაშია.\n\nდაჯავშნე უფასო კონსულტაცია და ნახე სად კარგავ გაყიდვებს.',
    book: 'კონსულტაციის დაჯავშნა',
    openDoor: 'გადადით WINSPACE-ზე',
    resumeTitle: 'მოკლე რეზიუმე',
    resumeText: [
      'ლაშა ხურციძე არის კომერციული დირექტორი, გაყიდვების სტრატეგი, მოლაპარაკებების ექსპერტი, ავტორი და Team4 — Sales College & Training Center-ის დამფუძნებელი. 15+ წლიანი გამოცდილებით ავტოინდუსტრიაში, დაზღვევაში, მშენებლობაში, ჰოსპიტალითი სფეროში, რითეილში და ბიზნეს განვითარების მიმართულებით, მან საკუთარი კარიერა რეალურ გაყიდვებზე, მოლაპარაკებებზე, ლიდერობასა და გუნდების განვითარებაზე ააგო.',
      'კარიერა დაიწყო პირდაპირი გაყიდვებიდან და ეტაპობრივად მივიდა სტრატეგიულ და მენეჯერულ პოზიციებამდე, რამაც მისცა შესაძლებლობა სიღრმისეულად შეესწავლა მომხმარებლის ფსიქოლოგია, კომუნიკაცია, გავლენა და ბიზნეს ზრდის მექანიზმები. წლების განმავლობაში მართავდა გაყიდვების დეპარტამენტებს, ავითარებდა ფილიალებს, მუშაობდა საერთაშორისო პარტნიორებთან და ქმნიდა ზრდაზე ორიენტირებულ სტრატეგიებს კონკურენტულ ბაზარზე.',
      'ლაშა ხურციძე ასევე არის წიგნის „მე ვარ პასუხი“ ავტორი — მოტივაციური და ფსიქოლოგიური ნაშრომის, რომელიც დაფუძნებულია რეალურ გამოცდილებაზე, გაყიდვებზე, ლიდერობაზე, რწმენაზე, ბრძოლაზე, პიროვნულ ტრანსფორმაციასა და წარმატების ფილოსოფიაზე.',
      'Team4 შეიქმნა არა როგორც ჩვეულებრივი ტრენინგ ცენტრი, არამედ როგორც სივრცე, სადაც გაყიდვები, კომუნიკაცია, მოლაპარაკებები და გავლენა ისწავლება რეალური პრაქტიკიდან და არა მხოლოდ თეორიიდან.',
    ],
    readMore: 'გაიგე მეტი',
    showLess: 'დაკეცვა',
    resumeBookCta: 'წიგნის შეძენა',
